### ISSUE TITLE
not working over https

### ISSUE THREAD

**Issue by mtliendo** [jsjoeio/react-use-sw-quote#1]
Yo! Awesome hook and its giving me lots of ideas!

Getting  a mixed-content error when trying this out since the api is [served over http](https://github.com/jsjoeio/react-use-sw-quote/blob/master/src/index.js#L11)

localhost will work since it's a trusted env, [but in my sandbox](https://codesandbox.io/s/use-sw-quote-guxtt), it doesn't 😢 

I was going to throw in a PR to fix, but I got a browser warning on google letting me know it wasn't trusted (I could click continue and it would work). 

Just a heads up for now, but if you're taking in PR's let me know!

**Comment by jsjoeio** [comment]
@mtliendo Thanks! Glad to hear that 😄

Oh noooo - of course - I only tested it locally so never encountered this issue 😅 

Totally open to a PR if you want! 🙏 I appreciate the heads up- I'll make a note next time I use this in a workshop! You rock, man!

**Comment by mtliendo** [comment]
Awesome! I'll push it out before noon tomorrow!

**Comment by mtliendo** [comment]
They don't have/have a bad cert :( So no `https` option

Maybe ask to use [these quotes](https://codepen.io/dhuddleston/pen/yegXEJ) instead?

**Comment by jsjoeio** [comment]
Aw, bummer! Feel free to submit a PR if that would work better! Otherwise, I'm not too worried. It's more for demo purposes

**Comment by mtliendo** [comment]
Closing since I don't have the time 😩
